### ISSUE TITLE
Any way to add MyLink or Tahoma to this? And update for PG3x?

### ISSUE THREAD

**Issue by rsphilli2112** [fahrer16/udi-somfy-poly#2]
@fahrer16   Is there anyway to update this to be able to add MyLink or Tahoma support?
Here's info for what can be pulled from the MyLink to possibly work - https://pypi.org/project/somfy-mylink/

Additionally, would like to see this updated with these to be available in the Polisy/eisy for PG3/PG3x.

**Comment by fahrer16** [comment]
Unfortunately, I no longer have any somfy shades and I actually no longer use any node servers, so this has been defunct for some time now.  Hopefully someone can fork it and update it to include some newer functionality and compatibility with polyglot 3.

**Comment by rsphilli2112** [comment]
Bummer. Thanks for letting me know.
